#!/bin/bash
#
#
###############################################
this is practice mode
we will try to study the basic shell scripting

we will try to execute the script by its own command on uppper hand


##############################################


set -x   #debug mode

df -h

free -g

nproc


ps

ps -ef

ps -ef | grep "ubuntu"


ps -ef | grep systemd | awk -F" " '{print$2}'

